apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/FriedrichMatheus/cloudflared-tunnel-k8s.git
    targetRevision: HEAD
    path: cloudflare
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      